# Autogenerated wrapper script for strobealign_jll for x86_64-linux-musl
export strobealign

using Zlib_jll
JLLWrappers.@generate_wrapper_header("strobealign")
JLLWrappers.@declare_executable_product(strobealign)
function __init__()
    JLLWrappers.@generate_init_header(Zlib_jll)
    JLLWrappers.@init_executable_product(
        strobealign,
        "bin/strobealign",
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
